apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    tekton.dev/pipeline: front-end-pipeline
  name: front-end-pipeline-firstrun
  namespace: bookstore-pipeline-demo
spec:
  params:
  - name: target-namespace
    value: bookstore-pipeline-demo
  pipelineRef:
    name: front-end-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: workspace-acme
    persistentVolumeClaim:
      claimName: fe-pipeline-pvc