
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: bookstore-fe
    app.kubernetes.io/component: bookstore-fe
    app.kubernetes.io/instance: bookstore-fe
  name: bookstore-fe
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: bookstore-fe:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:latest
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5