apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: bookstore-books-api
    app.kubernetes.io/component: bookstore-books-api
    app.kubernetes.io/instance: bookstore-books-api  
  name: bookstore-books-api
spec:
  lookupPolicy:
    local: false