apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: bookstore-books-api
    app.kubernetes.io/component: bookstore-books-api
    app.kubernetes.io/instance: bookstore-books-api
  name: bookstore-books-api
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: bookstore-books-api:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5